
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-20T11:47:34+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "a1499dd6e99de1325baa6f6036649c40ccb876a8",
 "version": "0.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
