
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-20T11:54:02-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "5be30b7c421be9c4c65f9a3163c30e32ddbe17be",
 "version": "0.16.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
