# coding: utf-8

"""
    IBM CLOUD PAK FOR DATA

    This is the Public API for IBM Cloud Pak for Data  # noqa: E501

    OpenAPI spec version: Beta
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class GetInstanceWithExtensionsResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'extensions': 'GetInstanceWithExtensionsResponseExtensions',
        'service_instance': 'ServiceInstance',
        'services_status': 'ServiceStatus'
    }

    attribute_map = {
        'extensions': 'extensions',
        'service_instance': 'service_instance',
        'services_status': 'services_status'
    }

    def __init__(self, extensions=None, service_instance=None, services_status=None):  # noqa: E501
        """GetInstanceWithExtensionsResponse - a model defined in Swagger"""  # noqa: E501

        self._extensions = None
        self._service_instance = None
        self._services_status = None
        self.discriminator = None

        if extensions is not None:
            self.extensions = extensions
        if service_instance is not None:
            self.service_instance = service_instance
        if services_status is not None:
            self.services_status = services_status

    @property
    def extensions(self):
        """Gets the extensions of this GetInstanceWithExtensionsResponse.  # noqa: E501


        :return: The extensions of this GetInstanceWithExtensionsResponse.  # noqa: E501
        :rtype: GetInstanceWithExtensionsResponseExtensions
        """
        return self._extensions

    @extensions.setter
    def extensions(self, extensions):
        """Sets the extensions of this GetInstanceWithExtensionsResponse.


        :param extensions: The extensions of this GetInstanceWithExtensionsResponse.  # noqa: E501
        :type: GetInstanceWithExtensionsResponseExtensions
        """

        self._extensions = extensions

    @property
    def service_instance(self):
        """Gets the service_instance of this GetInstanceWithExtensionsResponse.  # noqa: E501


        :return: The service_instance of this GetInstanceWithExtensionsResponse.  # noqa: E501
        :rtype: ServiceInstance
        """
        return self._service_instance

    @service_instance.setter
    def service_instance(self, service_instance):
        """Sets the service_instance of this GetInstanceWithExtensionsResponse.


        :param service_instance: The service_instance of this GetInstanceWithExtensionsResponse.  # noqa: E501
        :type: ServiceInstance
        """

        self._service_instance = service_instance

    @property
    def services_status(self):
        """Gets the services_status of this GetInstanceWithExtensionsResponse.  # noqa: E501


        :return: The services_status of this GetInstanceWithExtensionsResponse.  # noqa: E501
        :rtype: ServiceStatus
        """
        return self._services_status

    @services_status.setter
    def services_status(self, services_status):
        """Sets the services_status of this GetInstanceWithExtensionsResponse.


        :param services_status: The services_status of this GetInstanceWithExtensionsResponse.  # noqa: E501
        :type: ServiceStatus
        """

        self._services_status = services_status

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetInstanceWithExtensionsResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetInstanceWithExtensionsResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
