# coding: utf-8

"""
    IBM CLOUD PAK FOR DATA

    This is the Public API for IBM Cloud Pak for Data  # noqa: E501

    OpenAPI spec version: Beta
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class GuardiumTokenRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'client_id': 'str',
        'client_secret': 'str',
        'host': 'str',
        'password': 'str',
        'port': 'int',
        'username': 'str'
    }

    attribute_map = {
        'client_id': 'clientId',
        'client_secret': 'clientSecret',
        'host': 'host',
        'password': 'password',
        'port': 'port',
        'username': 'username'
    }

    def __init__(self, client_id=None, client_secret=None, host=None, password=None, port=None, username=None):  # noqa: E501
        """GuardiumTokenRequest - a model defined in Swagger"""  # noqa: E501

        self._client_id = None
        self._client_secret = None
        self._host = None
        self._password = None
        self._port = None
        self._username = None
        self.discriminator = None

        self.client_id = client_id
        self.client_secret = client_secret
        self.host = host
        self.password = password
        self.port = port
        self.username = username

    @property
    def client_id(self):
        """Gets the client_id of this GuardiumTokenRequest.  # noqa: E501

        user client id  # noqa: E501

        :return: The client_id of this GuardiumTokenRequest.  # noqa: E501
        :rtype: str
        """
        return self._client_id

    @client_id.setter
    def client_id(self, client_id):
        """Sets the client_id of this GuardiumTokenRequest.

        user client id  # noqa: E501

        :param client_id: The client_id of this GuardiumTokenRequest.  # noqa: E501
        :type: str
        """
        if client_id is None:
            raise ValueError("Invalid value for `client_id`, must not be `None`")  # noqa: E501

        self._client_id = client_id

    @property
    def client_secret(self):
        """Gets the client_secret of this GuardiumTokenRequest.  # noqa: E501

        user client secret  # noqa: E501

        :return: The client_secret of this GuardiumTokenRequest.  # noqa: E501
        :rtype: str
        """
        return self._client_secret

    @client_secret.setter
    def client_secret(self, client_secret):
        """Sets the client_secret of this GuardiumTokenRequest.

        user client secret  # noqa: E501

        :param client_secret: The client_secret of this GuardiumTokenRequest.  # noqa: E501
        :type: str
        """
        if client_secret is None:
            raise ValueError("Invalid value for `client_secret`, must not be `None`")  # noqa: E501

        self._client_secret = client_secret

    @property
    def host(self):
        """Gets the host of this GuardiumTokenRequest.  # noqa: E501

        Guardium host  # noqa: E501

        :return: The host of this GuardiumTokenRequest.  # noqa: E501
        :rtype: str
        """
        return self._host

    @host.setter
    def host(self, host):
        """Sets the host of this GuardiumTokenRequest.

        Guardium host  # noqa: E501

        :param host: The host of this GuardiumTokenRequest.  # noqa: E501
        :type: str
        """
        if host is None:
            raise ValueError("Invalid value for `host`, must not be `None`")  # noqa: E501

        self._host = host

    @property
    def password(self):
        """Gets the password of this GuardiumTokenRequest.  # noqa: E501

        Guardium password  # noqa: E501

        :return: The password of this GuardiumTokenRequest.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this GuardiumTokenRequest.

        Guardium password  # noqa: E501

        :param password: The password of this GuardiumTokenRequest.  # noqa: E501
        :type: str
        """
        if password is None:
            raise ValueError("Invalid value for `password`, must not be `None`")  # noqa: E501

        self._password = password

    @property
    def port(self):
        """Gets the port of this GuardiumTokenRequest.  # noqa: E501

        Guardium port  # noqa: E501

        :return: The port of this GuardiumTokenRequest.  # noqa: E501
        :rtype: int
        """
        return self._port

    @port.setter
    def port(self, port):
        """Sets the port of this GuardiumTokenRequest.

        Guardium port  # noqa: E501

        :param port: The port of this GuardiumTokenRequest.  # noqa: E501
        :type: int
        """
        if port is None:
            raise ValueError("Invalid value for `port`, must not be `None`")  # noqa: E501

        self._port = port

    @property
    def username(self):
        """Gets the username of this GuardiumTokenRequest.  # noqa: E501

        Guardium username  # noqa: E501

        :return: The username of this GuardiumTokenRequest.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this GuardiumTokenRequest.

        Guardium username  # noqa: E501

        :param username: The username of this GuardiumTokenRequest.  # noqa: E501
        :type: str
        """
        if username is None:
            raise ValueError("Invalid value for `username`, must not be `None`")  # noqa: E501

        self._username = username

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GuardiumTokenRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GuardiumTokenRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
