# coding: utf-8

"""
    IBM CLOUD PAK FOR DATA

    This is the Public API for IBM Cloud Pak for Data  # noqa: E501

    OpenAPI spec version: Beta
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class VolumeObject(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'resources': 'ResourceSection',
        'run_as_user': 'int'
    }

    attribute_map = {
        'resources': 'resources',
        'run_as_user': 'run_as_user'
    }

    def __init__(self, resources=None, run_as_user=None):  # noqa: E501
        """VolumeObject - a model defined in Swagger"""  # noqa: E501

        self._resources = None
        self._run_as_user = None
        self.discriminator = None

        if resources is not None:
            self.resources = resources
        if run_as_user is not None:
            self.run_as_user = run_as_user

    @property
    def resources(self):
        """Gets the resources of this VolumeObject.  # noqa: E501


        :return: The resources of this VolumeObject.  # noqa: E501
        :rtype: ResourceSection
        """
        return self._resources

    @resources.setter
    def resources(self, resources):
        """Sets the resources of this VolumeObject.


        :param resources: The resources of this VolumeObject.  # noqa: E501
        :type: ResourceSection
        """

        self._resources = resources

    @property
    def run_as_user(self):
        """Gets the run_as_user of this VolumeObject.  # noqa: E501

        the file server started is run as this UID. This user needs to be  within range 1000320900 to 1000361000 if cpd-user-scc is used  # noqa: E501

        :return: The run_as_user of this VolumeObject.  # noqa: E501
        :rtype: int
        """
        return self._run_as_user

    @run_as_user.setter
    def run_as_user(self, run_as_user):
        """Sets the run_as_user of this VolumeObject.

        the file server started is run as this UID. This user needs to be  within range 1000320900 to 1000361000 if cpd-user-scc is used  # noqa: E501

        :param run_as_user: The run_as_user of this VolumeObject.  # noqa: E501
        :type: int
        """

        self._run_as_user = run_as_user

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(VolumeObject, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VolumeObject):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
