# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kaskada/kaskada/v1alpha/sources.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from kaskada.kaskada.v1alpha import pulsar_pb2 as kaskada_dot_kaskada_dot_v1alpha_dot_pulsar__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%kaskada/kaskada/v1alpha/sources.proto\x12\x17kaskada.kaskada.v1alpha\x1a$kaskada/kaskada/v1alpha/pulsar.proto\"\x97\x01\n\x06Source\x12\x42\n\x07kaskada\x18\x01 \x01(\x0b\x32&.kaskada.kaskada.v1alpha.KaskadaSourceH\x00R\x07kaskada\x12?\n\x06pulsar\x18\x02 \x01(\x0b\x32%.kaskada.kaskada.v1alpha.PulsarSourceH\x00R\x06pulsarB\x08\n\x06source\"\x0f\n\rKaskadaSource\"M\n\x0cPulsarSource\x12=\n\x06\x63onfig\x18\x01 \x01(\x0b\x32%.kaskada.kaskada.v1alpha.PulsarConfigR\x06\x63onfigB\xfc\x01\n\x1b\x63om.kaskada.kaskada.v1alphaB\x0cSourcesProtoP\x01ZQgithub.com/kaskada-ai/kaskada/gen/proto/go/kaskada/kaskada/v1alpha;kaskadav1alpha\xa2\x02\x03KKX\xaa\x02\x17Kaskada.Kaskada.V1alpha\xca\x02\x17Kaskada\\Kaskada\\V1alpha\xe2\x02#Kaskada\\Kaskada\\V1alpha\\GPBMetadata\xea\x02\x19Kaskada::Kaskada::V1alphab\x06proto3')



_SOURCE = DESCRIPTOR.message_types_by_name['Source']
_KASKADASOURCE = DESCRIPTOR.message_types_by_name['KaskadaSource']
_PULSARSOURCE = DESCRIPTOR.message_types_by_name['PulsarSource']
Source = _reflection.GeneratedProtocolMessageType('Source', (_message.Message,), {
  'DESCRIPTOR' : _SOURCE,
  '__module__' : 'kaskada.kaskada.v1alpha.sources_pb2'
  # @@protoc_insertion_point(class_scope:kaskada.kaskada.v1alpha.Source)
  })
_sym_db.RegisterMessage(Source)

KaskadaSource = _reflection.GeneratedProtocolMessageType('KaskadaSource', (_message.Message,), {
  'DESCRIPTOR' : _KASKADASOURCE,
  '__module__' : 'kaskada.kaskada.v1alpha.sources_pb2'
  # @@protoc_insertion_point(class_scope:kaskada.kaskada.v1alpha.KaskadaSource)
  })
_sym_db.RegisterMessage(KaskadaSource)

PulsarSource = _reflection.GeneratedProtocolMessageType('PulsarSource', (_message.Message,), {
  'DESCRIPTOR' : _PULSARSOURCE,
  '__module__' : 'kaskada.kaskada.v1alpha.sources_pb2'
  # @@protoc_insertion_point(class_scope:kaskada.kaskada.v1alpha.PulsarSource)
  })
_sym_db.RegisterMessage(PulsarSource)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\033com.kaskada.kaskada.v1alphaB\014SourcesProtoP\001ZQgithub.com/kaskada-ai/kaskada/gen/proto/go/kaskada/kaskada/v1alpha;kaskadav1alpha\242\002\003KKX\252\002\027Kaskada.Kaskada.V1alpha\312\002\027Kaskada\\Kaskada\\V1alpha\342\002#Kaskada\\Kaskada\\V1alpha\\GPBMetadata\352\002\031Kaskada::Kaskada::V1alpha'
  _SOURCE._serialized_start=105
  _SOURCE._serialized_end=256
  _KASKADASOURCE._serialized_start=258
  _KASKADASOURCE._serialized_end=273
  _PULSARSOURCE._serialized_start=275
  _PULSARSOURCE._serialized_end=352
# @@protoc_insertion_point(module_scope)
