# Generated by Django 4.2 on 2023-04-24 14:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_cupcake_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newcake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=20)),
                ('weight', models.FloatField()),
                ('image', models.ImageField(upload_to='images/cakes')),
                ('writer', models.CharField(max_length=20, null=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'NewCake',
            },
        ),
        migrations.AlterField(
            model_name='cupcake',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
