# Generated by Django 2.0.2 on 2023-04-24 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0004_cupcake_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newcake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('weight', models.FloatField()),
                ('image', models.ImageField(upload_to='images/cakes')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'NewCake',
            },
        ),
    ]
