VERSION_YEAR = 2023
VERSION_MONTH = int('04')
VERSION_DAY = int('22')
VERSION_HOUR = int('07')
VERSION_MINUTE = int('38')
MAJOR_VERSION = 1
MINOR_VERSION = 13
PATCH_VERSION = 202304220738
version_date = '2023/04/22 07:38'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
