
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-20T10:59:01-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "d3939f6c813a06538f2f39aa7583ac9869adbb95",
 "version": "1.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
