{
    'name': 'Odoo Instance',
    'version': '14.0.0.1.0',
    'category': 'Project',
    'summary': 'Manage Odoo instances with relevant information',
    'author': 'Coopdevs',
    'website': 'https://www.coopdevs.org',
    'depends': ['base', 'contract', 'project', 'calendar'],
    'data': [
        'security/ir.model.access.csv',
        'security/security_groups.xml',
        'views/project_instance_view.xml',        
        'views/project_module_view.xml',
        'views/project_instance_window_wizard_view.xml',
        'views/odoo_version_view.xml',
        'views/project_process_view.xml',
        'data/ir.cron.xml',
        'data/calendar_tags.xml',
        'data/odoo_version_data.xml',
        'data/odoo14_core_modules_app_data.xml',
        'data/odoo12_core_modules_data.xml',
    ],
    # set icon
    'images': ['static/src/img/icon.png'],
    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'AGPL-3',
}
