# Generated by ariadne-codegen on 2023-04-24 15:32
# Source: ./operations.graphql

from pydantic import Field

from .base_model import BaseModel


class PingIntegrationConnection(BaseModel):
    ping_integration_connection: "PingIntegrationConnectionPingIntegrationConnection" = Field(
        alias="pingIntegrationConnection"
    )


class PingIntegrationConnectionPingIntegrationConnection(BaseModel):
    duration: float


PingIntegrationConnection.update_forward_refs()
PingIntegrationConnectionPingIntegrationConnection.update_forward_refs()
