VERSION_YEAR = 2023
VERSION_MONTH = int('04')
VERSION_DAY = int('21')
VERSION_HOUR = int('16')
VERSION_MINUTE = int('44')
MAJOR_VERSION = 1
MINOR_VERSION = 13
PATCH_VERSION = 202304211644
version_date = '2023/04/21 16:44'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
