# Generated by ariadne-codegen on 2023-04-24 15:32
# Source: ./operations.graphql

from typing import Any

from pydantic import Field

from .base_model import BaseModel


class SendIntegrationRequest(BaseModel):
    send_integration_request: "SendIntegrationRequestSendIntegrationRequest" = Field(
        alias="sendIntegrationRequest"
    )


class SendIntegrationRequestSendIntegrationRequest(BaseModel):
    response: Any


SendIntegrationRequest.update_forward_refs()
SendIntegrationRequestSendIntegrationRequest.update_forward_refs()
