"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 9.3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.customer_support_customer import CustomerSupportCustomer
globals()['CustomerSupportCustomer'] = CustomerSupportCustomer
from apideck.model.get_customer_support_customer_response import GetCustomerSupportCustomerResponse


class TestGetCustomerSupportCustomerResponse(unittest.TestCase):
    """GetCustomerSupportCustomerResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetCustomerSupportCustomerResponse(self):
        """Test GetCustomerSupportCustomerResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetCustomerSupportCustomerResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
