VERSION_YEAR = 2023
VERSION_MONTH = int('04')
VERSION_DAY = int('20')
VERSION_HOUR = int('06')
VERSION_MINUTE = int('09')
MAJOR_VERSION = 1
MINOR_VERSION = 13
PATCH_VERSION = 202304200609
version_date = '2023/04/20 06:09'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
