# coding: utf-8

from __future__ import annotations

import re  # noqa: F401
from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from fastapi_camelcase import CamelModel  # noqa: F401
from pydantic import AnyUrl, Field


class ConstraintRef(CamelModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ConstraintRef - a model defined in OpenAPI

        id: The id of this ConstraintRef.
        href: The href of this ConstraintRef [Optional].
        name: The name of this ConstraintRef [Optional].
        version: The version of this ConstraintRef [Optional].
        base_type: The base_type of this ConstraintRef [Optional].
        schema_location: The schema_location of this ConstraintRef [Optional].
        type: The type of this ConstraintRef [Optional].
        referred_type: The referred_type of this ConstraintRef [Optional].
    """

    id: str
    href: Optional[str] = None
    name: Optional[str] = None
    version: Optional[str] = None
    base_type: Optional[str] = None
    schema_location: Optional[AnyUrl] = None
    type: Optional[str] = Field(default=None, alias='@type')
    referred_type: Optional[str] = Field(default=None, alias='@referredType')


ConstraintRef.update_forward_refs()
