VERSION_YEAR = 2023
VERSION_MONTH = int('04')
VERSION_DAY = int('23')
VERSION_HOUR = int('06')
VERSION_MINUTE = int('28')
MAJOR_VERSION = 1
MINOR_VERSION = 4
PATCH_VERSION = 202304230628
version_date = '2023/04/23 06:28'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
