VERSION_YEAR = 2023
VERSION_MONTH = int('04')
VERSION_DAY = int('20')
VERSION_HOUR = int('05')
VERSION_MINUTE = int('41')
MAJOR_VERSION = 0
MINOR_VERSION = 27
PATCH_VERSION = 202304200541
version_date = '2023/04/20 05:41'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
