__title__ = 'mindsdb_text_to_sql'
__package_name__ = 'mindsdb_text_to_sql'
__version__ = '0.1.0'
__description__ = "MindsDB Text to SQL, converts natural language to SQL code."
__email__ = "minurapunchihewa17@gmail.com"
__author__ = 'Minura Punchihewa'
__github__ = 'https://github.com/MinuraPunchihewa/mindsdb-text-to-sql'
__pypi__ = 'https://pypi.org/project/mindsdb-text-to-sql/'
__license__ = None
__copyright__ = None