# coding: utf-8

"""
    Marqeta Core API

    Simplified management of your payment programs  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Contact: dev@swadesh.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
from inspect import getfullargspec
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictBool

class UserValidationResponse(BaseModel):
    """
    UserValidationResponse
    """
    birth_date: StrictBool = Field(..., description="yyyy-MM-dd")
    phone: StrictBool = Field(..., description="10 char max, phone number")
    ssn: StrictBool = Field(..., description="Last four digits of SSN")
    random_name_line1_postfix: StrictBool = Field(..., description="Six-char random name postfix")
    __properties = ["birth_date", "phone", "ssn", "random_name_line1_postfix"]

    class Config:
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> UserValidationResponse:
        """Create an instance of UserValidationResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> UserValidationResponse:
        """Create an instance of UserValidationResponse from a dict"""
        if obj is None:
            return None

        if type(obj) is not dict:
            return UserValidationResponse.parse_obj(obj)

        _obj = UserValidationResponse.parse_obj({
            "birth_date": obj.get("birth_date") if obj.get("birth_date") is not None else False,
            "phone": obj.get("phone") if obj.get("phone") is not None else False,
            "ssn": obj.get("ssn") if obj.get("ssn") is not None else False,
            "random_name_line1_postfix": obj.get("random_name_line1_postfix") if obj.get("random_name_line1_postfix") is not None else False
        })
        return _obj

