
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-23T18:12:21-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "12792a8feff8bb82c805e0ab0555fd56facb207c",
 "version": "0.0.8.dev20230420"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
