from currency_codes.models import Currency


def get_crypto_currencies() -> list[Currency]:
    return _crypto_currencies


_crypto_currencies: list[Currency] = [
    Currency(name="Bitcoin", code="BTC", numeric_code=None, minor_units=8),
    Currency(name="Ethereum", code="ETH", numeric_code=None, minor_units=18),
    Currency(name="Binance Coin", code="BNB", numeric_code=None, minor_units=18),
    Currency(name="Cardano", code="ADA", numeric_code=None, minor_units=18),
    Currency(name="XRP", code="XRP", numeric_code=None, minor_units=6),
    Currency(name="Solana", code="SOL", numeric_code=None, minor_units=9),
    Currency(name="Polkadot", code="DOT", numeric_code=None, minor_units=10),
    Currency(name="Dogecoin", code="DOGE", numeric_code=None, minor_units=8),
    Currency(name="USD Coin", code="USDC", numeric_code=None, minor_units=6),
    Currency(name="Terra", code="LUNA", numeric_code=None, minor_units=6),
    Currency(name="Uniswap", code="UNI", numeric_code=None, minor_units=18),
    Currency(name="Litecoin", code="LTC", numeric_code=None, minor_units=8),
    Currency(name="Bitcoin Cash", code="BCH", numeric_code=None, minor_units=8),
    Currency(name="Polygon", code="MATIC", numeric_code=None, minor_units=18),
    Currency(name="Wrapped Bitcoin", code="WBTC", numeric_code=None, minor_units=8),
    Currency(name="Cosmos", code="ATOM", numeric_code=None, minor_units=6),
    Currency(name="FTX Token", code="FTT", numeric_code=None, minor_units=18),
    Currency(name="Avalanche", code="AVAX", numeric_code=None, minor_units=18),
    Currency(name="Chainlink", code="LINK", numeric_code=None, minor_units=18),
    Currency(name="SHIBA INU", code="SHIB", numeric_code=None, minor_units=18),
    Currency(name="Ethereum Classic", code="ETC", numeric_code=None, minor_units=18),
    Currency(name="TRON", code="TRX", numeric_code=None, minor_units=6),
    Currency(name="Internet Computer", code="ICP", numeric_code=None, minor_units=8),
    Currency(name="Bitcoin SV", code="BSV", numeric_code=None, minor_units=8),
    Currency(name="PancakeSwap", code="CAKE", numeric_code=None, minor_units=18),
    Currency(name="Fantom", code="FTM", numeric_code=None, minor_units=18),
    Currency(name="Filecoin", code="FIL", numeric_code=None, minor_units=18),
    Currency(name="Dai", code="DAI", numeric_code=None, minor_units=18),
    Currency(name="UNUS SED LEO", code="LEO", numeric_code=None, minor_units=2),
    Currency(name="Huobi Token", code="HT", numeric_code=None, minor_units=18),
    Currency(name="Aave", code="AAVE", numeric_code=None, minor_units=18),
    Currency(name="OKB", code="OKB", numeric_code=None, minor_units=2),
    Currency(name="The Open Network", code="TON", numeric_code=None, minor_units=2),
    Currency(name="Kusama", code="KSM", numeric_code=None, minor_units=12),
    Currency(name="Theta Network", code="THETA", numeric_code=None, minor_units=18),
    Currency(name="Compound", code="COMP", numeric_code=None, minor_units=18),
    Currency(name="NEO", code="NEO", numeric_code=None, minor_units=0),
    Currency(name="Binance USD", code="BUSD", numeric_code=None, minor_units=18),
    Currency(name="Elrond", code="EGLD", numeric_code=None, minor_units=18),
    Currency(name="Dash", code="DASH", numeric_code=None, minor_units=8),
    Currency(name="Zcash", code="ZEC", numeric_code=None, minor_units=8),
    Currency(name="Bitcoin Cash ABC", code="BCHA", numeric_code=None, minor_units=8),
    Currency(name="Chiliz", code="CHZ", numeric_code=None, minor_units=8),
    Currency(name="Telcoin", code="TEL", numeric_code=None, minor_units=2),
    Currency(name="Waves", code="WAVES", numeric_code=None, minor_units=8),
    Currency(name="TrueUSD", code="TUSD", numeric_code=None, minor_units=18),
    Currency(name="BitTorrent", code="BTT", numeric_code=None, minor_units=6),
    Currency(name="Decred", code="DCR", numeric_code=None, minor_units=8),
    Currency(name="Hedera Hashgraph", code="HBAR", numeric_code=None, minor_units=8),
    Currency(name="SushiSwap", code="SUSHI", numeric_code=None, minor_units=18),
    Currency(name="Helium", code="HNT", numeric_code=None, minor_units=18),
    Currency(name="Qtum", code="QTUM", numeric_code=None, minor_units=8),
    Currency(name="Holo", code="HOT", numeric_code=None, minor_units=18),
    Currency(name="Paxos Standard", code="PAX", numeric_code=None, minor_units=18),
    Currency(name="Stacks", code="STX", numeric_code=None, minor_units=6),
    Currency(name="UMA", code="UMA", numeric_code=None, minor_units=18),
    Currency(name="Ravencoin", code="RVN", numeric_code=None, minor_units=8),
    Currency(name="Nano", code="NANO", numeric_code=None, minor_units=30),
    Currency(name="Zilliqa", code="ZIL", numeric_code=None, minor_units=12),
    Currency(name="Kava.io", code="KAVA", numeric_code=None, minor_units=6),
    Currency(name="Bitcoin Gold", code="BTG", numeric_code=None, minor_units=8),
    Currency(name="renBTC", code="RENBTC", numeric_code=None, minor_units=8),
    Currency(name="Hive", code="HIVE", numeric_code=None, minor_units=3),
    Currency(name="Horizen", code="ZEN", numeric_code=None, minor_units=8),
    Currency(name="Monero", code="XMR", numeric_code=None, minor_units=12),
    Currency(name="Nexus Mutual", code="NXM", numeric_code=None, minor_units=18),
    Currency(name="Arweave", code="AR", numeric_code=None, minor_units=12),
    Currency(name="Curve DAO Token", code="CRV", numeric_code=None, minor_units=18),
    Currency(name="Ocean Protocol", code="OCEAN", numeric_code=None, minor_units=18),
    Currency(name="MaidSafeCoin", code="MAID", numeric_code=None, minor_units=8),
    Currency(name="Storj", code="STORJ", numeric_code=None, minor_units=8),
    Currency(name="Siacoin", code="SC", numeric_code=None, minor_units=24),
    Currency(name="Enzyme", code="MLN", numeric_code=None, minor_units=18),
    Currency(name="NKN", code="NKN", numeric_code=None, minor_units=18),
    Currency(name="HUSD", code="HUSD", numeric_code=None, minor_units=8),
    Currency(name="iExec RLC", code="RLC", numeric_code=None, minor_units=9),
    Currency(name="Bancor", code="BNT", numeric_code=None, minor_units=18),
    Currency(name="Livepeer", code="LPT", numeric_code=None, minor_units=18),
    Currency(name="Algorand", code="ALGO", numeric_code=None, minor_units=6),
    Currency(name="Ardor", code="ARDR", numeric_code=None, minor_units=8),
    Currency(name="Golem", code="GLM", numeric_code=None, minor_units=18),
    Currency(name="The Graph", code="GRT", numeric_code=None, minor_units=18),
    Currency(name="Ren", code="REN", numeric_code=None, minor_units=18),
    Currency(name="IoTeX", code="IOTX", numeric_code=None, minor_units=18),
    Currency(name="Fetch.ai", code="FET", numeric_code=None, minor_units=18),
    Currency(name="Staked Ether", code="STETH", numeric_code=None, minor_units=18),
    Currency(name="Nexo", code="NEXO", numeric_code=None, minor_units=18),
    Currency(name="BakeryToken", code="BAKE", numeric_code=None, minor_units=18),
    Currency(name="Measurable Data Token", code="MDT", numeric_code=None, minor_units=18),
]
