# Generated by Django 4.1.7 on 2023-04-05 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiToken",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_on", models.DateTimeField(auto_now=True, db_index=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "token_id",
                    models.CharField(
                        db_index=True,
                        max_length=40,
                        unique=True,
                        verbose_name="Token_Id",
                    ),
                ),
                ("token", models.CharField(max_length=256, verbose_name="Token")),
                ("revoked", models.BooleanField(default=False, verbose_name="Revoked")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User token",
                "verbose_name_plural": "User tokens",
            },
        ),
    ]
