# coding: utf-8

from __future__ import annotations

import re  # noqa: F401
from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from fastapi_camelcase import CamelModel  # noqa: F401
from pydantic import AnyUrl, Field


class ServiceQualificationItemRelationship(CamelModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ServiceQualificationItemRelationship - a model defined in OpenAPI

        id: The id of this ServiceQualificationItemRelationship [Optional].
        relationship_type: The relationship_type of this ServiceQualificationItemRelationship [Optional].
        base_type: The base_type of this ServiceQualificationItemRelationship [Optional].
        schema_location: The schema_location of this ServiceQualificationItemRelationship [Optional].
        type: The type of this ServiceQualificationItemRelationship [Optional].
    """

    id: Optional[str] = None
    relationship_type: Optional[str] = None
    base_type: Optional[str] = None
    schema_location: Optional[AnyUrl] = None
    type: Optional[str] = Field(default=None, alias='@type')


ServiceQualificationItemRelationship.update_forward_refs()
