
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-21T17:19:26-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "b64be73fa730ab23f9434cab6b857c9c3ec0c8b0",
 "version": "2.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
