VERSION_YEAR = 2023
VERSION_MONTH = int('04')
VERSION_DAY = int('24')
VERSION_HOUR = int('16')
VERSION_MINUTE = int('46')
MAJOR_VERSION = 1
MINOR_VERSION = 4
PATCH_VERSION = 202304241646
version_date = '2023/04/24 16:46'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
