
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-24T07:42:58-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "53d572666c0d93a0da065eff1fe22a02bed92296",
 "version": "1.8.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
