# coding: utf-8

"""
    Marqeta Core API

    Simplified management of your payment programs  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Contact: dev@swadesh.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
from inspect import getfullargspec
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, StrictStr
from marqeta_client.models.tabapay_ptc_address import TabapayPTCAddress
from marqeta_client.models.tabapay_soft_descriptor_phone import TabapaySoftDescriptorPhone

class TabapaySoftDescriptor(BaseModel):
    """
    TabapaySoftDescriptor
    """
    name: Optional[StrictStr] = None
    address: Optional[TabapayPTCAddress] = None
    phone: Optional[TabapaySoftDescriptorPhone] = None
    email: Optional[StrictStr] = None
    __properties = ["name", "address", "phone", "email"]

    class Config:
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> TabapaySoftDescriptor:
        """Create an instance of TabapaySoftDescriptor from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of address
        if self.address:
            _dict['address'] = self.address.to_dict()
        # override the default output from pydantic by calling `to_dict()` of phone
        if self.phone:
            _dict['phone'] = self.phone.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TabapaySoftDescriptor:
        """Create an instance of TabapaySoftDescriptor from a dict"""
        if obj is None:
            return None

        if type(obj) is not dict:
            return TabapaySoftDescriptor.parse_obj(obj)

        _obj = TabapaySoftDescriptor.parse_obj({
            "name": obj.get("name"),
            "address": TabapayPTCAddress.from_dict(obj.get("address")) if obj.get("address") is not None else None,
            "phone": TabapaySoftDescriptorPhone.from_dict(obj.get("phone")) if obj.get("phone") is not None else None,
            "email": obj.get("email")
        })
        return _obj

