# coding: utf-8

"""
    Cakemail API

    The Cakemail API exposes multiple APIs including Authentication, Marketing, Contact, Transactional, Analytic, Content, Account and Partner.  # noqa: E501

    The version of the OpenAPI document: 1.12.14
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from cakemail_openapi.configuration import Configuration


class ContactsExportFullResponse(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'str',
        'status': 'ContactsExportStatus',
        'description': 'str',
        'segment_id': 'int',
        'filter': 'str',
        'query': 'str',
        'fiql': 'str',
        'json': 'object',
        'created_on': 'int',
        'expires_on': 'int',
        'progress': 'float'
    }

    attribute_map = {
        'id': 'id',
        'status': 'status',
        'description': 'description',
        'segment_id': 'segment_id',
        'filter': 'filter',
        'query': 'query',
        'fiql': 'fiql',
        'json': 'json',
        'created_on': 'created_on',
        'expires_on': 'expires_on',
        'progress': 'progress'
    }

    def __init__(self, id=None, status=None, description=None, segment_id=None, filter=None, query=None, fiql=None, json=None, created_on=None, expires_on=None, progress=None, local_vars_configuration=None):  # noqa: E501
        """ContactsExportFullResponse - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._status = None
        self._description = None
        self._segment_id = None
        self._filter = None
        self._query = None
        self._fiql = None
        self._json = None
        self._created_on = None
        self._expires_on = None
        self._progress = None
        self.discriminator = None

        self.id = id
        self.status = status
        if description is not None:
            self.description = description
        if segment_id is not None:
            self.segment_id = segment_id
        if filter is not None:
            self.filter = filter
        if query is not None:
            self.query = query
        if fiql is not None:
            self.fiql = fiql
        if json is not None:
            self.json = json
        self.created_on = created_on
        self.expires_on = expires_on
        self.progress = progress

    @property
    def id(self):
        """Gets the id of this ContactsExportFullResponse.  # noqa: E501


        :return: The id of this ContactsExportFullResponse.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ContactsExportFullResponse.


        :param id: The id of this ContactsExportFullResponse.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and id is None:  # noqa: E501
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def status(self):
        """Gets the status of this ContactsExportFullResponse.  # noqa: E501


        :return: The status of this ContactsExportFullResponse.  # noqa: E501
        :rtype: ContactsExportStatus
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this ContactsExportFullResponse.


        :param status: The status of this ContactsExportFullResponse.  # noqa: E501
        :type: ContactsExportStatus
        """
        if self.local_vars_configuration.client_side_validation and status is None:  # noqa: E501
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def description(self):
        """Gets the description of this ContactsExportFullResponse.  # noqa: E501


        :return: The description of this ContactsExportFullResponse.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ContactsExportFullResponse.


        :param description: The description of this ContactsExportFullResponse.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def segment_id(self):
        """Gets the segment_id of this ContactsExportFullResponse.  # noqa: E501


        :return: The segment_id of this ContactsExportFullResponse.  # noqa: E501
        :rtype: int
        """
        return self._segment_id

    @segment_id.setter
    def segment_id(self, segment_id):
        """Sets the segment_id of this ContactsExportFullResponse.


        :param segment_id: The segment_id of this ContactsExportFullResponse.  # noqa: E501
        :type: int
        """

        self._segment_id = segment_id

    @property
    def filter(self):
        """Gets the filter of this ContactsExportFullResponse.  # noqa: E501


        :return: The filter of this ContactsExportFullResponse.  # noqa: E501
        :rtype: str
        """
        return self._filter

    @filter.setter
    def filter(self, filter):
        """Sets the filter of this ContactsExportFullResponse.


        :param filter: The filter of this ContactsExportFullResponse.  # noqa: E501
        :type: str
        """

        self._filter = filter

    @property
    def query(self):
        """Gets the query of this ContactsExportFullResponse.  # noqa: E501


        :return: The query of this ContactsExportFullResponse.  # noqa: E501
        :rtype: str
        """
        return self._query

    @query.setter
    def query(self, query):
        """Sets the query of this ContactsExportFullResponse.


        :param query: The query of this ContactsExportFullResponse.  # noqa: E501
        :type: str
        """

        self._query = query

    @property
    def fiql(self):
        """Gets the fiql of this ContactsExportFullResponse.  # noqa: E501


        :return: The fiql of this ContactsExportFullResponse.  # noqa: E501
        :rtype: str
        """
        return self._fiql

    @fiql.setter
    def fiql(self, fiql):
        """Sets the fiql of this ContactsExportFullResponse.


        :param fiql: The fiql of this ContactsExportFullResponse.  # noqa: E501
        :type: str
        """

        self._fiql = fiql

    @property
    def json(self):
        """Gets the json of this ContactsExportFullResponse.  # noqa: E501


        :return: The json of this ContactsExportFullResponse.  # noqa: E501
        :rtype: object
        """
        return self._json

    @json.setter
    def json(self, json):
        """Sets the json of this ContactsExportFullResponse.


        :param json: The json of this ContactsExportFullResponse.  # noqa: E501
        :type: object
        """

        self._json = json

    @property
    def created_on(self):
        """Gets the created_on of this ContactsExportFullResponse.  # noqa: E501


        :return: The created_on of this ContactsExportFullResponse.  # noqa: E501
        :rtype: int
        """
        return self._created_on

    @created_on.setter
    def created_on(self, created_on):
        """Sets the created_on of this ContactsExportFullResponse.


        :param created_on: The created_on of this ContactsExportFullResponse.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and created_on is None:  # noqa: E501
            raise ValueError("Invalid value for `created_on`, must not be `None`")  # noqa: E501

        self._created_on = created_on

    @property
    def expires_on(self):
        """Gets the expires_on of this ContactsExportFullResponse.  # noqa: E501


        :return: The expires_on of this ContactsExportFullResponse.  # noqa: E501
        :rtype: int
        """
        return self._expires_on

    @expires_on.setter
    def expires_on(self, expires_on):
        """Sets the expires_on of this ContactsExportFullResponse.


        :param expires_on: The expires_on of this ContactsExportFullResponse.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and expires_on is None:  # noqa: E501
            raise ValueError("Invalid value for `expires_on`, must not be `None`")  # noqa: E501

        self._expires_on = expires_on

    @property
    def progress(self):
        """Gets the progress of this ContactsExportFullResponse.  # noqa: E501


        :return: The progress of this ContactsExportFullResponse.  # noqa: E501
        :rtype: float
        """
        return self._progress

    @progress.setter
    def progress(self, progress):
        """Sets the progress of this ContactsExportFullResponse.


        :param progress: The progress of this ContactsExportFullResponse.  # noqa: E501
        :type: float
        """
        if self.local_vars_configuration.client_side_validation and progress is None:  # noqa: E501
            raise ValueError("Invalid value for `progress`, must not be `None`")  # noqa: E501

        self._progress = progress

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ContactsExportFullResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ContactsExportFullResponse):
            return True

        return self.to_dict() != other.to_dict()
