#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['mvm']

package_data = \
{'': ['*']}

package_dir = \
{'': 'src'}

install_requires = \
['matplotlib==3.7.0',
 'pyDOE==0.3.8',
 'scikit-fuzzy==0.4.2',
 'smt==1.1.0',
 'multiprocess==0.70.12.2']

extras_require = \
{'doc': ['sphinx', 'sphinx-autobuild', 'nbsphinx'],
 'test': ['pytest>=6.2.5',
          'pytest-cov==3.0.0',
          'pytest-dependency==0.5.1',
          'pandoc']}

setup(name='mvmlib',
      version='0.5.9',
      description='Margin Value Method Library',
      author=None,
      author_email='Khalil Al Handawi <khalil.alhandawi@mail.mcgill.ca>',
      url=None,
      packages=packages,
      package_data=package_data,
      package_dir=package_dir,
      install_requires=install_requires,
      extras_require=extras_require,
      python_requires='>=3.8',
     )
